### ISSUE TITLE
OpenAPI Spec integration

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#26]
Investigate https://github.com/cdimascio/express-openapi-validator#example-express-api-server
vs https://github.com/jquense/yup

for format validation

**Comment by thaigillespie** [comment]
So here is my comment regarding whether we should use express-openapi-validator or yup for our server-side validation after reading through their github's README and stuff:

- express-openapi-validator: This is more suitable if we want a more centralized approach to request, response validation. With this, we can define an api.yaml that holds all validation information for all of our endpoints, for all the type of requests we want to make on those endpoints. Here is an example of an api.yaml file given by the maintainers of experss-openapi-validator's github repo (https://github.com/cdimascio/express-openapi-validator/blob/master/examples/1-standard/api.yaml). So, if we want things to be organized in one file (or there is a way to combine several .yaml files into 1, like importing components to an index.js file) then I think express-openapi-validator is very good for our use case because it can cover all of our endpoints in a very complete manner without being verbose or a hassle. However, keep in mind that our .yaml file might look messy as we have more and more endpoints.

- yup: This is more suitable if we want a more decentralized approach to server-side validation. With yup, one can only create a schema object at a time. Therefore, if one wants to validate any response or request for an endpoint, one will need to write a yup schema object for it, individually. In the worst case scenario, if there are n number of requests and responses to validate, one needs to write n yup schema objects. I think yup will work well when we only have certain requests or responses for an endpoint that we want to have validation for, otherwise there would be too many schema.js files and it would be very hard to manage whenever we want to make a considerable (big) change to what we have in our request body and responses.

Overall, it really depends on how much validation we want to have for our endpoints. If we have a lot, express-openapi-validator is better, if we don't want to have validation for a lot of our endpoints, then yup is probably better. Some additional factors to consider, but probably should not have too much weight on our decision on what to use: 

-  express-openapi-validator only has 284 stars, while yup has 10.2k stars.
- On yup's github README, it is said that yup's main use case is client side validation.

**Comment by godwinpang** [comment]
hey some great points here; I'd like to raise a couple of things to give some more context

@your concern about openapi yaml growing without bound: completely valid point - within the OpenAPI spec I know you can use $refs to combine yaml files but it looks like expressopenapivalidator only supports one big yaml file. We should be able to look into something like [speccy](https://github.com/wework/speccy) and use it in our build pipeline to resolve the refs in our yaml files to consolidate before serving. That way we keep the small yamls for dev but serve the big one for validation + docs.

One other big point with OpenAPI is that it serves not only as validation, but also a *specification* for your API including error codes and responses; that's greatly different than something like yup which only validates the requests and responses as individual entities.

There might be value in something like yup to provide more complex validation rules (e.g. email or some regex) since OpenAPI spec only supports validation of type/required fields.

Might be worth looking into [joi](https://hapi.dev/module/joi/); TLDR yup for server-side.

**Comment by godwinpang** [comment]
onboarding both introduces the issue of perhaps having to redefine your schemas in two places so that's something to take into consideration as well. maybe openapi spec is good enough then? we don't have to onboard speccy until the yaml grows too big; we can worry about big yaml files when it becomes a problem as long as there is a clear solution in the form of speccy

side-project idea: extend openapi spec to support email validation/regex validation
