### ISSUE TITLE
teapot

### ISSUE THREAD

**Issue by godwinpang** [HKN-UCSD/hkn-server#31]
https://tools.ietf.org/html/rfc2324

teapots are great

**Comment by godwinpang** [comment]
this is meme but would honestly be a pretty good first timer issue, any takers @jyang58 @AneeshJalan? essentially we can just have a teapot endpoint that returns the teapot http code

**Comment by thaigillespie** [comment]
For this issue, I think it would be best to create a teapot controller with base endpoint as `/api/teapot`. Then, make a function that handles a GET request on to the endpoint `/api/teapot`. You can use any one of EventController, UserController and AuthController as reference. I recommend AuthController because it has the least code out of the three, so you won't be too overwhelmed with the amount of new code, but honestly do whatever you think is right :) Just ping dev chat if you need any help. Good luck!
